export const familyMembers = [
  { name: "Lorena Fautsch Garza", bloodType: "O+" },
  { name: "Gaby Cantu Canales", bloodType: "O+" },
  { name: "Ana Sofia Gonzalez Romero", bloodType: "O+" },
  { name: "Sergio Treviño Castro", bloodType: "O+" },
  { name: "Patricio Fernando Sada Garza", bloodType: "O+" },
  { name: "Raquel Garza Gonzalez", bloodType: "O+" },
  { name: "David Helis Barbosa Ibarra", bloodType: "O+" },
  { name: "Mara De la Vega Chazaro", bloodType: "O+" },
  { name: "Monica Alejandra Gonzalez Garza", bloodType: "O+" },
  { name: "Mariana Garza Gonzalez", bloodType: "O+" },
  { name: "Adrian Marcelo Elosua Rodriguez", bloodType: "O+" },
  { name: "Marian Chávez Elizondo", bloodType: "O+" },
  { name: "Eric Vincent Garza Garcia", bloodType: "O+" },
  { name: "Ricardo Fautsch Garza", bloodType: "O+" },
  { name: "Regina Garza Gonzalez", bloodType: "O+" },
  { name: "Artemio Garza De la Puente", bloodType: "O-" },
  { name: "David Garza Romo", bloodType: "No sé" },
  { name: "Milarca Fernandez Zambrano", bloodType: "No sé" },
  { name: "Artemio Jesus Garza Rodríguez", bloodType: "No sé" },
  { name: "Alfonso Garza de la Puente", bloodType: "No sé" },
  { name: "Ricardo Jose Garza Rodriguez", bloodType: "B+" },
  { name: "Ana Catalina Garza Rodriguez", bloodType: "B+" },
  { name: "Antonio David Garza Rodriguez", bloodType: "B+" },
  { name: "Mónica Alejandra Garza González", bloodType: "B+" },
  { name: "Alma Nora Garza Obregón", bloodType: "B+" },
  { name: "Ana Llaguno Benavides", bloodType: "B+" },
  { name: "Oscar Adrian Garza Garza", bloodType: "B-" },
  { name: "Andres Garza de la Puente", bloodType: "B-" },
  { name: "Jorge Angel Villarreal Garza", bloodType: "B-" },
  { name: "Michelle Angela Santos", bloodType: "B-" },
  { name: "Eugenio Garza De la puente", bloodType: "AB+" },
  { name: "Javier Garcia Garza", bloodType: "AB+" },
  { name: "Paulina García Garza", bloodType: "AB+" },
  { name: "RICARDO JOSE GARZA ROMO", bloodType: "AB+" },
  { name: "Jorge Artemio Garza Garza", bloodType: "AB-" },
  { name: "Ivonne Fautsch Garza", bloodType: "A+" },
  { name: "Martha Margarita Garza Rodriguez", bloodType: "A+" },
  { name: "Jorge Artemio Garza Rodriguez", bloodType: "A+" },
  { name: "Oscar Javier Odriozola De la Torre", bloodType: "A+" },
  { name: "Emilio Fautsch Muguira", bloodType: "A+" },
  { name: "Mauricio Ayala Gonzalez", bloodType: "A+" },
  { name: "Valerie Toussaint Nasta", bloodType: "A+" },
  { name: "Maria de Lourdes de la Puente Bay", bloodType: "A+" },
  { name: "Kattia Garza Romo", bloodType: "A+" },
  { name: "Maria Teresa Romo Velhagen", bloodType: "A+" },
  { name: "Alma Nora Garza Garza", bloodType: "A+" },
  { name: "Santiago Paras Fautsch", bloodType: "A+" },
  { name: "Javier Garcia Robles Gil", bloodType: "A-" },
  { name: "Martha Alejandra Garcia Garza", bloodType: "A-" },
  { name: "Adrian Marcelo Elosua García", bloodType: "No sé" },
  { name: "Albana Garza Fernandez", bloodType: "No sé" },
  { name: "Alegra Garza Fernandez", bloodType: "No sé" },
  { name: "Alfonso Garza Llaguno", bloodType: "No sé" },
  { name: "Alondra Garza Fernandez", bloodType: "No sé" },
  { name: "Álvaro Garza Llaguno", bloodType: "No sé" },
  { name: "Ana Lucia Villarreal Garza", bloodType: "No sé" },
  { name: "Aneska Garza Fernandez", bloodType: "No sé" },
  { name: "Ariana Elizondo Fautsch", bloodType: "No sé" },
  { name: "Artemio Tomas Garza Garcia", bloodType: "No sé" },
  { name: "Camila Garcia Cantú", bloodType: "No sé" },
  { name: "Cordelia Garza de la Vega", bloodType: "No sé" },
  { name: "Diego Belden de la Vega", bloodType: "No sé" },
  { name: "Diego Fautsch Toussaint", bloodType: "No sé" },
  { name: "Diego García Cantu", bloodType: "No sé" },
  { name: "Elena Villarreal Garza", bloodType: "No sé" },
  { name: "Emilio Fautsch Toussaint", bloodType: "No sé" },
  { name: "Federico Elosua García", bloodType: "No sé" },
  { name: "Gabriel Villarreal Garza", bloodType: "No sé" },
  { name: "Gonzalo Garza González", bloodType: "No sé" },
  { name: "Guillermo Cueva Garza", bloodType: "No sé" },
  { name: "Isabel Garza de la Vega", bloodType: "No sé" },
  { name: "Javier García Cantu", bloodType: "No sé" },
  { name: "Jerónimo Garza González", bloodType: "No sé" },
  { name: "Jorge Artemio Garza Chavez", bloodType: "No sé" },
  { name: "Lia Garza Chavez", bloodType: "No sé" },
  { name: "Loretta Treviño Garza", bloodType: "No sé" },
  { name: "Mara Victoria Garza de la Vega", bloodType: "No sé" },
  { name: "Milarca Cueva Garza", bloodType: "No sé" },
  { name: "Natalia Paras Fautsch", bloodType: "No sé" },
  { name: "Pablo Fautsch Toussaint", bloodType: "No sé" },
  { name: "Raquel Garza Chavez", bloodType: "No sé" },
  { name: "Raquel Garza González", bloodType: "No sé" },
  { name: "Roberta Garza Junco", bloodType: "No sé" },
  { name: "Rodrigo Elosua García", bloodType: "No sé" },
  { name: "Sergio Treviño Garza", bloodType: "No sé" },
  { name: "Sofia Garza Junco", bloodType: "No sé" },
  { name: "Vanessa Garza Junco", bloodType: "No sé" },
  { name: "Vicente Flagler Garza Garcia", bloodType: "No sé" },
  { name: "Vivianne Cueva Garza", bloodType: "No sé" },
];
